# Generated by Django 5.0.2 on 2024-04-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_user_otp_user_otp_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, null=True),
        ),
    ]
